### ISSUE TITLE
update SmartCyp to CDK 2.9 (or better)

### ISSUE THREAD

**Issue by tdudgeon** [cdk/nwo-openscience-2024#22]
SmartCyp uses the 1.4 API and 1.5+ can't be used. 
https://smartcyp.sund.ku.dk/mol_to_som

**Comment by egonw** [comment]
Source code: http://smartcyp2.sund.ku.dk/download.php

**Comment by egonw** [comment]
~Also needs JChemPaint.~

Also needs the JChemPaint-originating rendering stack, but that is actually part of the CDK.

**Comment by egonw** [comment]
Downstream users: Bioclipse (Bacting!) and this: https://github.com/christinadebruynkops/GLORYx/tree/a1f4a8246e09eb971aac88d29123f59f2ad33944

**Comment by egonw** [comment]
We're running into character encoding issues:

```
[ERROR] /home/egonw/var/Projects/Other/smartcyp/src/main/java/smartcyp/MoleculeKU.java:[1084,118] unmappable character (0x96) for encoding UTF-8
[ERROR] /home/egonw/var/Projects/Other/smartcyp/src/main/java/smartcyp/MoleculeKU.java:[1084,1388] unmappable character (0x96) for encoding UTF-8
[ERROR] /home/egonw/var/Projects/Other/smartcyp/src/main/java/smartcyp/MoleculeKU.java:[1088,140] unmappable character (0x96) for encoding UTF-8
[ERROR] /home/egonw/var/Projects/Other/smartcyp/src/main/java/smartcyp/MoleculeKU.java:[1092,120] unmappable character (0x96) for encoding UTF-8
[ERROR] /home/egonw/var/Projects/Other/smartcyp/src/main/java/smartcyp/MoleculeKU.java:[1096,515] unmappable character (0x96) for encoding UTF-8
```

**Comment by jmillanacosta** [comment]
- [x] Create repository (https://github.com/cdk/smartcyp) to track changes
- [x] [Create POM to manage dependencies](https://github.com/cdk/smartcyp/commit/f20b9cafa0139273665bec9fe561ca788a354a4f)

**Comment by egonw** [comment]
I started this monitoring report: https://github.com/cdk/nwo-openscience-2024/blob/main/monitoring/smartcyp.md

**Comment by egonw** [comment]
Update to CDK 2.1 fails with a missing dependency:

```
[ERROR] Failed to execute goal on project smartcyp: Could not resolve dependencies for project io.github.cdk.smartcyp:smartcyp:jar:2.5.0-SNAPSHOT: The following artifacts could not be resolved: uk.ac.ebi.beam:beam-core:jar:1.1-SNAPSHOT, uk.ac.ebi.beam:beam-func:jar:1.1-SNAPSHOT: Could not find artifact uk.ac.ebi.beam:beam-core:jar:1.1-SNAPSHOT in ossrh (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

**Comment by egonw** [comment]
Update to CDK 2.2 fails with the following, which will be fixed when I further clean up the use of builders and a single (`silent`?) data model implementation: 

```
Exception in thread "main" java.lang.ClassCastException: class org.openscience.cdk.AtomContainer2$BaseAtomRef cannot be cast to class org.openscience.cdk.Atom (org.openscience.cdk.AtomContainer2$BaseAtomRef and org.openscience.cdk.Atom are in unnamed module of loader 'app')
        at smartcyp.MoleculeKU.assignAtomEnergies(MoleculeKU.java:229)
        at smartcyp.SMARTCyp.main(SMARTCyp.java:210)
```

**Comment by egonw** [comment]
> Update to CDK 2.2 fails with the following

Fixed by refactoring the code to use interfaces as much as possible: https://github.com/cdk/smartcyp/commit/e96a1f0ae98494a057b17bef06e9811c35c1a91a

**Comment by egonw** [comment]
Okay, I got it compiling with CDK 2.9 and the calculations seem to run okay, but the rendering worked still okay with 2.2 but is not ideal with 2.9:

![image](https://github.com/cdk/nwo-openscience-2024/assets/26721/2cee4655-7b17-4499-af33-6eb93f092acd)

**Comment by egonw** [comment]
Task: https://github.com/cdk/nwo-openscience-2024/issues/26

**Comment by egonw** [comment]
@tdudgeon, this would be a good time to give the new a first spin.

**Comment by egonw** [comment]
Look up past code examples: https://github.com/cdk/nwo-openscience-2024/issues/30
